# Generated by Django 3.2 on 2021-04-28 16:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_auto_20210428_1619'),
    ]

    operations = [
        migrations.AlterField(
            model_name='app',
            name='url',
            field=models.URLField(default='www.google.com'),
        ),
    ]
