# Generated by Django 3.2 on 2021-04-28 16:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_app_app_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='app',
            name='app_id',
            field=models.IntegerField(default=1, unique=True),
        ),
    ]
